### ISSUE TITLE
VisionFive 2 compatible

### ISSUE THREAD

**Issue by strlcat** [dramforever/opensbi-h#3]
Good day,

I would like to know if it was tested only on VF1 or VF2 can also be used?
Can you look into their repo https://github.com/starfive-tech/opensbi/tree/JH7110_VisionFive2_devel, there seem not so much commits since VF1 times.

Also I have VF2 at hand and I can serve as a guinea pig if you're interested.

Thank you.

**Comment by dramforever** [comment]
Hi, thanks for your interest. I haven't received the hardware yet and haven't had much time to continue developing this project mainly due to lack of practical applications (too slow for practical use). However if you rebase my branch on top of their OpenSBI branch I'd expect it to work. Happy to provide assistance if you do want to try it out.

**Comment by strlcat** [comment]
Hi,
How can I git rebase against upstream? Sorry, I'm quite newb to advanced git :)

**Comment by dramforever** [comment]
Hi, I've both rebased `soft-hext` against upstream master and created a branch [`soft-hext-rebase-vf2`](https://github.com/dramforever/opensbi-h/tree/soft-hext-rebase-vf2) that's rebased against StarFive's `JH7110_VisionFive2_devel`. You can check it out

**Comment by strlcat** [comment]
I guess I've booted okay but I somehow need to blacklist `0x13e000000` 8192 pages out in my devicetree. Can you help me with it, so I don't have to limit my Linux to `mem=2G`? (otherwise it tries to access the pages and panics)

**Comment by strlcat** [comment]
Nevermind memory trouble, I did blacklist it myself with statement like this:
```
                hextpages@13e000000 {
                        compatible = "removed-dma-pool";
                        no-map;
                        reg = <0x01 0x3e000000 0x00 0x2000000>;
                };
```
and now my VF2's OpenSBI looks like:
```
OpenSBI v1.2
   ____                    _____ ____ _____
  / __ \                  / ____|  _ \_   _|
 | |  | |_ __   ___ _ __ | (___ | |_) || |
 | |  | | '_ \ / _ \ '_ \ \___ \|  _ < | |
 | |__| | |_) |  __/ | | |____) | |_) || |_
  \____/| .__/ \___|_| |_|_____/|____/_____|
        | |
        |_|

sbi_hext_init: Hypervisor extension emulation enabled.
Platform Name             : StarFive VisionFive V2
Platform Features         : medeleg
Platform HART Count       : 5
Platform IPI Device       : aclint-mswi
Platform Timer Device     : aclint-mtimer @ 4000000Hz
Platform Console Device   : uart8250
Platform HSM Device       : jh7110-hsm
Platform PMU Device       : ---
Platform Reboot Device    : pm-reset
Platform Shutdown Device  : pm-reset
Firmware Base             : 0x40000000
Firmware Size             : 416 KB
Firmware RW Offset        : 0x40000
Runtime SBI Version       : 1.0

Domain0 Name              : root
Domain0 Boot HART         : 3
Domain0 HARTs             : 0*,1*,2*,3*,4*
Domain0 Region00          : 0x0000000002000000-0x000000000200ffff M: (I,R,W) S/U: ()
Domain0 Region01          : 0x0000000040000000-0x000000004003ffff M: (R,X) S/U: ()
Domain0 Region02          : 0x0000000040040000-0x000000004007ffff M: (R,W) S/U: ()
Domain0 Region03          : 0x000000013e000000-0x000000013fffffff M: (R,W,X) S/U: (R)
Domain0 Region04          : 0x0000000000000000-0xffffffffffffffff M: (R,W,X) S/U: (R,W,X)
Domain0 Next Address      : 0x0000000040200000
Domain0 Next Arg1         : 0x0000000042200000
Domain0 Next Mode         : S-mode
Domain0 SysReset          : yes

Boot HART ID              : 3
Boot HART Domain          : root
Boot HART Priv Version    : v1.11
Boot HART Base ISA        : rv64imafdcbx
Boot HART ISA Extensions  : none
Boot HART PMP Count       : 8
Boot HART PMP Granularity : 4096
Boot HART PMP Address Bits: 34
Boot HART MHPM Count      : 2
Boot HART MIDELEG         : 0x0000000000000222
Boot HART MEDELEG         : 0x000000000000b109

Hypervisor Extension      : Emulated
Shadow PT Space Base      : 0x13e000000
Shadow PT Space Size      : 8192 pages
```
with successfully booting U-Boot and Linux as next OS to bash prompt.
Didn't tried KVM tho, because 5.15.x tree lacks `arch/riscv/kvm`.

**Comment by dramforever** [comment]
> I guess I've booted okay but I somehow need to blacklist `0x13e000000` 8192 pages out in my devicetree. Can you help me with it, so I don't have to limit my Linux to `mem=2G`? (otherwise it tries to access the pages and panics)

I think what you did was fine. Normally OpenSBI-H sets the reserved memory and u-boot forwards it on even if you load a new device tree. I guess u-boot might also need an updating here, though that would likely depend on starfive getting a newer u-boot working.

**Comment by strlcat** [comment]
I guess my test was fine, but I don't use it atm because we're in VF2 community are still stuck to vendor provided 5.15.x kernel where there is simply no KVM for riscv (for us, ordinary users). Once mainline support will be there I will revisit the project to host things on it. Thank you!
